### ISSUE TITLE
Implement Heston model

### ISSUE THREAD

**Issue by mvanzulli** [JuliaQuant/FinancialDerivatives.jl#21]
Implement Heston model via FFT according to [this ref](https://arxiv.org/vc/arxiv/papers/1502/1502.02963v1.pdf)

**Comment by iblislin** [comment]
well, seems the ref is gone? I got 502 from that link

**Comment by mvanzulli** [comment]
> well, seems the ref is gone? I got 502 from that link

Yep you are right, I've updated the link 🛠️

**Comment by iblislin** [comment]
ah thanks! let me study it first.

**Comment by mvanzulli** [comment]
> ah thanks! let me study it first.

Sure, no rush. Thanks for your attention to this matter 🤙🏼
