### ISSUE TITLE
Fix pages deployment 

### ISSUE THREAD

**Issue by mvanzulli** [JuliaQuant/FinancialDerivatives.jl#26]

**Comment by iblislin** [comment]
well, it's just a typo in README

```patch
- [dev-url]: https://JuliaQunat.github.io/FinancialDerivatives.jl/dev/
+ [dev-url]: https://JuliaQuant.github.io/FinancialDerivatives.jl/dev/
```

**Comment by mvanzulli** [comment]
> well, it's just a typo in README
> 
> ```diff
> - [dev-url]: https://JuliaQunat.github.io/FinancialDerivatives.jl/dev/
> + [dev-url]: https://JuliaQuant.github.io/FinancialDerivatives.jl/dev/
> ```

Thanks for spotting that out, I've opened this MR: https://github.com/JuliaQuant/FinancialDerivatives.jl/pull/27
